### ISSUE TITLE
Method #5 (start_domain_test) cant be run using API.md

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-backend#104]
This document (https://github.com/dotse/zonemaster-backend/blob/master/docs/API.md) needs to have functioning examples (that are always updated if the API changes). When I try to run method "start_domain_test" it returns:

{"error":{"message":"Failed to parse json","code":-32700}} 

Please add a working example to the document (if some API-calls need a previous call to work, like "get_test" etc, then please note that in the document and try to have an existing call to create a test exists before that).

**Comment by pawal** [comment]
Just a note on API changes. The API should not change in a minor release - it should always require a major release. This is described in the [Versions and Releases](https://github.com/dotse/zonemaster/blob/master/docs/design/Versions%20and%20Releases.md) document.
