### ISSUE TITLE
Experimental method #9 (create_user) cant be run using API.md

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-backend#108]
I would love to be able to test this one also (I expect it can take a bunch of domains as input and somehow "tag" them for later identification and retrieval?) so please do document its' parameters better (or simply have a working example use with 2+ simple domains in it).

**Comment by cdybedahl** [comment]
Unfortunately, this method does not do what you hope. The functionality you're thinking of is not currently exposed via this API.
