### ISSUE TITLE
Zonemaster crashes constantly in Free BSD on using mysql 

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#123]
From peter Larsen
==============

i need to be able to show more debugging to see why it’s crashing all the time.

the zonemaster-cli seems to work just fine, it’s the gui, backend, engine that interact poorly with something .. and crashes.. constantly..

I’m using mysql as backend, 5.6

I have see this:

DBD::mysql::db selectrow_array failed: fetch() without execute() at /usr/local/lib/perl5/site_perl/Zonemaster/WebBackend/DB/MySQL.pm line 163.
DBD::mysql::db selectrow_array failed: fetch() without execute() at /usr/local/lib/perl5/site_perl/Zonemaster/WebBackend/DB/MySQL.pm line 163.
DBD::mysql::db selectrow_array failed: MySQL server has gone away at /usr/local/lib/perl5/site_perl/Zonemaster/WebBackend/DB/MySQL.pm line 130.
DBD::mysql::db selectrow_array failed: MySQL server has gone away at /usr/local/lib/perl5/site_perl/Zonemaster/WebBackend/DB/MySQL.pm line 130.

zonemaster was freshly installed today with github, on a freebsd 10.2-RELEASE

**Comment by mtoma** [comment]
Reproduced as generic on all supported platforms. It crashes nearly all the time.

**Comment by mtoma** [comment]
The PostgreSQL Backend also has this bug. It crashes during a stress test:
DBD::Pg::st DESTROY failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request. at lib//Zonemaster/WebBackend/DB.pm line 63.
        (in cleanup) DBD::Pg::st DESTROY failed: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request. at lib//Zonemaster/WebBackend/DB.pm line 63.
DBD::Pg::db do failed: no connection to the server at lib//Zonemaster/WebBackend/DB.pm line 64.
DBD::Pg::db do failed: no connection to the server at lib//Zonemaster/WebBackend/DB.pm line 64.
