### ISSUE TITLE
Publish to CPAN

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#160]
There's no release of zonemaster-backend on cpan. Is it possible to publish the latest tarball to cpan please?

**Comment by sandoche2k** [comment]
Anand ... I will inform the concerned developer and get back to you with a
timeline.

Sandoche.

**Comment by mtoma** [comment]
Issue on github created.
Will be published on CPAN.

----- Original Message -----

**Comment by matsduf** [comment]
@sandoche2k and I will create a CPAN Pause account for Zonemaster. Before that is in place I think it is best to publish it with the IIS account as with Zonemaster Engine. If the backend is ready for publication at CPAN I suggest that we do that as a new release at the same time as we publish the upcoming release of the Engine. I think @sandoche2k and I will do that next week (last week of June 2016).

**Comment by mtoma** [comment]
I think it is better to wait a few days for the zonemaster account. It takes only a few days to be created as it needs to be validated by the pause administrator.
It will save us the work needed to transfer a package from one account to another.

**Comment by aabdnn** [comment]
Hello guys. I see that Zonemaster-backend still isn't in CPAN. When do you think you will publish it?

**Comment by sandoche2k** [comment]
Hi Anand,

   Sorry for the delay. The responsible person is on vacation. I will keep
you updated as soon as i get a definite date.

Sandoche.
