### ISSUE TITLE
.sql files belong in "share", not doc

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#165]
The .sql files supplied in the "docs" directory are actually scripts that a user should run the first time, after installing the backend. As such, they are not documentation, and should be installing into a "share" directory by the makefile.

At the moment, if I install the backend directly from a tarball (and eventually from CPAN), these .sql files are not present in the installation, so I can't use them.

**Comment by matsduf** [comment]
Update installation doc and installation script.
