### ISSUE TITLE
The JSON-RPC Call 7: get_test_results returns is inconsistently documented

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-backend#169]
The levels of an JSON-RPC Call 7: get_test_results are inconsistently documented.

In https://github.com/dotse/zonemaster-backend/blob/master/docs/API.md it says under "JSON-RPC Call 7: get_test_results" and "Description of the results":

> The level is the level of severity of the message
> 
>    NOTICE, INFO are considered OK: green
>    WARNING as warning: orange
>    ERROR as error: red

In https://github.com/dotse/zonemaster-backend/blob/master/docs/notes_api.md it says "get_test_results", "Output" and "result":

> A list of objects representing the results of the test. Each object has three keys, module, 
> message and level. The values of them are strings. The module is the test module that 
> produced the result, the level is the severity of the message as set in the policy used 
> (that is, one of the strings DEBUG, INFO, NOTICE, WARNING, ERROR and 
> CRITICAL) and message is a human-readable text describing that particular result.

The documents must be in sync.

**Comment by sandoche2k** [comment]
Close when #176 is completed

**Comment by mattias-p** [comment]
So which ones are the legal severity levels really? Is it possible to specify severity levels as inputs somewhere so I can test and see what really happens?

**Comment by mattias-p** [comment]
I don't see being resolved for 2016.2. Can it be moved to 2017.1?

**Comment by matsduf** [comment]
This is not urgent. Moved to 2017.1.

**Comment by matsduf** [comment]
The updates of the API documents has made this issue irrelevant. I close it.
