### ISSUE TITLE
Documentation for profile is missing

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-backend#172]
JSON-RPC Call 5: start_domain_test supports key/parameter "profile" that can have one of the values 'default_profile', 'test_profile_1' and 'test_profile_2'. ('test_profile_2' is actually excuted as equal to 'default_profile'.)

It should be documented the format of such profile, the name of such profile file ("iana-profile.json") and where they are to be put.

**Comment by matsduf** [comment]
See #176

**Comment by sandoche2k** [comment]
Close when #176 is completed

**Comment by mattias-p** [comment]
The format is described here: https://github.com/dotse/zonemaster-engine/blob/master/docs/ConfigAndPolicy.pod.
The file locations still needs documentation. This belongs in the zonemaster repo.

**Comment by matsduf** [comment]
See https://github.com/dotse/zonemaster/issues/498
