### ISSUE TITLE
Filters feature

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#174]
In DNScheck, there is a filter feature, which allows more fine-grained control over certain tests. For example at the RIPE NCC, when we do pre-delegation checks, and one of the name servers is "ns.ripe.net" then we wish to downgrade any errors for it from ERROR or CRITICAL to WARNING, because we know that the server isn't yet configured for the zone.

We need to be able to do something similar in Zonemaster, in order to migrate from DNScheck to Zonemaster.

However, this feature in Zonemaster should be tied to the profiles in some way, so that the filter is only active for a certain profile (pre-delegation check), but not for regular checks (where we DO want to flag an error with ns.ripe.net).

Is this possible?

**Comment by sandoche2k** [comment]
Hi Anand,

    The issue has already been added to the issue list "
https://github.com/dotse/zonemaster-engine/issues/206".  I think the issue
should be part of the Engine code. Hence, I will add your explanations into
the same issue (#206).

     After our discussion with you during RIPE-72, myselves and Patrik are
convinced we should have this feature.

     We have a telephone meeting next thursday. I hope to give you a update
by next friday morning.

Sandoche.

**Comment by aabdnn** [comment]
Thank you Sandoche! I look forward to your update.

**Comment by sandoche2k** [comment]
fixed by https://github.com/dotse/zonemaster-engine/pull/211

**Comment by sandoche2k** [comment]
Filters feature is possible from the engine using the option "zonemaster-cli --config". It should be possible to do the same from the backend.

**Comment by aabdnn** [comment]
Hey guys, any update on this?

**Comment by mtoma** [comment]
Hi Anand,
Please let me know if you need any help with the usage of this new feature.

**Comment by aabdnn** [comment]
Hi Michal. Yes, I do need help with this feature. I have a custom config, called predelegation.json, stored in /etc/zonemaster.
So how exactly do I refer to this file in /etc/zonemaster/backend_config.ini ?
