### ISSUE TITLE
Document "add_api_user" and "add_batch_job" completely

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#185]
Please update the API documentation to explain that "add_api_user" only works from "localhost".

Please also document how to use "add_batch_job".

**Comment by mattias-p** [comment]
@mtoma Could you fix some spelling errors here? Search for ”bach”, ”thesting” and ”qith”.

Also `get_batch_job_result` has a note on restrictions for when it will create users. That should probably be taken out.
