### ISSUE TITLE
Why is "ip" required in "start_domain_test" ?

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#186]
With zonemaster-cli, I can pass name servers for a test like this:

zonemaster-cli <domain> --ns <ns1> --ns <ns2>

I don't need to specify any IP addresses for these name servers (unless the name servers are in-zone).

However, when submitting the same check to the backend with "start_domain_test", it insists that I provide IP addresses. Why does the backend do this?

**Comment by mtoma** [comment]
The zonemaster-backend was first developed only to suit the zonemaster-frontend needs.
This can be easily changed now that the backend is also used in a more generic way.

**Comment by aabdnn** [comment]
Hi Michal. Did you make any code changes to make "ip" optional?

**Comment by sandoche2k** [comment]
Could be closed if issue #210 is closed
