### ISSUE TITLE
s/professes/processes/

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#188]
Several files in the project refer to "number_of_professes_for_frontend_testing" and similarly for batch processing.

I suspect that "professes" should be "processes". Is my assumption correct?

**Comment by mtoma** [comment]
Yes of course!

**Comment by aabdnn** [comment]
Okay, so will you run a recursive sed? :)

**Comment by mtoma** [comment]
Well unfortunately not only as I need to make sure the fix will not break existing installations.
