### ISSUE TITLE
The add_batch_job API takes hours to schedule several hundread thousand domains for thesting

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#191]

**Comment by mtoma** [comment]
create index test_results__hash_id ON test_results (hash_id, creation_time);
create index test_results__params_deterministic_hash ON test_results (params_deterministic_hash);

**Comment by matsduf** [comment]
Update the installation process so that either the indexes are created automatically or that the installation document contains instructions how to create them.

I assume that having the indexes is useful even if batching is not used.
