### ISSUE TITLE
API: ds_digest_pairs still disabled?

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#192]
The current documentation of the API for "start_domain_test" says that ds_digest_pairs is disabled. We require this functionality to be able to do predelegation testing of reverse zones being requested in the RIPE Database. What is the reason for disabling this functionality, and when will you enable it?

**Comment by mtoma** [comment]
No this is just a documentation bug. It is enabled.

**Comment by mtoma** [comment]
Fixed on the latest documentation.
