### ISSUE TITLE
Not permitted to create a new batch

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-backend#208]
I have one batch running (or actually got stuck, see #207, and then I want to run another one, but I may not:

```
$ curl -H "Content-Type: application/json" -d @add_batch_job--10001-domains.json http://localhost:8080/ ; echo; echo ; echo
{"jsonrpc":"2.0","error":{"message":"You can't create a new batch job, job:[7] started on:[2016-11-09 10:39:02] still running  at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB/MySQL.pm line 89.\n","code":-32603},"id":"MD4712"}
```

I this a policy issue or a technical issue?

**Comment by mtoma** [comment]
This is a policy issue and is due to the previous error. A batch user is permitted to have only one simultaneous batch job running. Is considered running any batch job that has at least one test with progress < 100.
