### ISSUE TITLE
Create a config_file parameter allowing a backend to execute only tests of a certain priority

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#211]
This is a temporary workaround until a proper queue+priority is implemented

**Comment by mattias-p** [comment]
Could you update this issue to explicitly state the following?
* the name of the option
* under what section it's located
* its allowed values
* whether it's supposed to be optional or required
* possibly what default value to expect

**Comment by matsduf** [comment]
What the backend is about to have is queue handling and make it possible to let different workers handle different queue. I see no reason why this should be temporary. And let us call this "queue" not "priority". That is less confusing for the users. I know that the field in the database is called "priority".

**Comment by mtoma** [comment]
You are probably right Mats, I'll call this queue and add the another column to the database.
