### ISSUE TITLE
Scalar "params"-values

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-backend#228]
The API documentation claims that it follows the JSON-RPC 2.0 specification, but a few violations have been spotted. The spec requires the value of `"params"` to be a structured value. The following methods violate that requirement:

* `get_batch_job_result`
* `get_data_from_parent_zone`
* `get_ns_ips`
* `test_progress`

In my opinion this should be fixed as part of a bigger effort to make the API more concise.

**Comment by sandoche2k** [comment]
Update the API to make "params" as a JSON object

**Comment by pamasse** [comment]
@mattias-p We discussed that for modification on the API documentation, we must based the pull-request on the profiles branch. It's the same for the code ? or based my pull request on develop ?

**Comment by matsduf** [comment]
I think the code could be merged to the develop branch if it works on its own, i.e. it does not require tome other changes that we do not hve time to complete.

**Comment by mattias-p** [comment]
@pamasse This is scheduled to be merged for 2018.1. While the documentation for the profiles feature is scheduled to be completed for the same release, that documentation should not be merged without the implementation also being complete.

On the other hand this change is pretty much guaranteed to overlap with the validation layer, so it'll be easier on our brains if we don't develop them simultaneously but rather one before the other.

**Comment by sandoche2k** [comment]
@pamasse close?

**Comment by matsduf** [comment]
@sandoche2k, I think this issue can be closed when #399 is merged.

**Comment by sandoche2k** [comment]
Closed with https://github.com/dotse/zonemaster-backend/pull/399
