### ISSUE TITLE
Deprecate "test_profile_2"

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-backend#229]
Currently the `"test_profile_2"` and `"default_profile"` profiles give identical behaviors. The redundant `"test_profile_2"` profile should be deprecated.

* The documentation should be updated to declare that the `"test_profile_2"` profile has been deprecated and that the `"default_profile"` profile can be used as a drop-in replacement.
* A release note or migration guide should be written to make sure that users don't end up with inaccessible test results in their database after the `"test_profile_2"` profile has been completely removed.
* When the `"test_profile_2"` profile is received as an argument to an RPC method, a warning should be written to the log file, telling what RPC method recieved it, that the `"test_profile_2"` profile is deprecated and that the `"default_profile"` profile can be used as a drop-in replacement. Affected methods: `add_batch_job`, `get_test_history` and `start_domain_test`.
* Once the deprecation warning has been logged, the profile argument should be updated so that the `"default_profile"` is used internally. Affected methods: `add_batch_job`, `get_test_history` and `start_domain_test`.

See #171.

In my opinion this should be fixed as part of a bigger effort to make the API more concise.

**Comment by mattias-p** [comment]
Are some of these steps overkill at this stage? Someone decide if any of these bullests should be struck.

**Comment by mtoma** [comment]
For me it is perfectly ok to just state that test_profile_2 is reserved for future use and should never be used.

----- Original Message -----

**Comment by matsduf** [comment]
Why not just remove it (deprecate it)? If we need it in the future, we could add it again.

**Comment by mtoma** [comment]
Yes, or completely remove it from the documentation.

----- Original Message -----

**Comment by mattias-p** [comment]
I think zero undocumented features is a good metric to aim for.

**Comment by sandoche2k** [comment]
Will be solved by https://github.com/dotse/zonemaster/issues/498
