### ISSUE TITLE
Deprecate validate_syntax

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-backend#231]
The `validate_syntax` API method is no longer useful. On the other hand it increases the burden of maintaining the public interfaces (documentation, extensibility, potential for bugs etc). The `validate_syntax` API method should be deprecated.

In my opinion this should be fixed as part of a bigger effort to make the API more concise.

**Comment by sandoche2k** [comment]
agreed during the F2F.

**Comment by pamasse** [comment]
Can be closed ?

**Comment by matsduf** [comment]
Resolved by #411.
