### ISSUE TITLE
Commands for creating the database are not installed properly while installing from CPAN

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#241]
Normally, all the required scripts should be found under the directory "Zonemaster-WebBackend"

But scripts for creating the database like "initial-postgres.sql" are not found here. On running "find" we find it in this directory "/root/.cpan/build/Zonemaster-WebBackend-1.0.7-nv3Euo/docs/initial-postgres.sql"

In that case, the installation instructions for the backend does not work properly

@mattias-p  Is it working for you in freebsd with the following command 
"psql -U pgsql -f ./initial-postgres.sql template1"
And, what is template1 ?

**Comment by mtoma** [comment]
The database installation instructions are now in the share directory.
If they are not than it means you are not testing the latest version. This is probably the case as the latest version is not on CPAN.

----- Original Message -----

**Comment by sandoche2k** [comment]
i am installing from CPAN

**Comment by sandoche2k** [comment]
@matsduf @mattias-p As mentioned at the start of this discussion, if we install from CPAN then the database initalising or cleaning instructions are not stored in the directory, where it is intended to. Either as @mtoma mentioned, he updates the CPAN, so that the files are stored in the intended place (or) we install the backend using make. Which one would you guys prefer?

**Comment by matsduf** [comment]
@sandoche2k and @mattias-p! If I understand @mtoma the files will be in the correct place after next release. If we intend the installation document for next release it should be fine, shouldn't it?

**Comment by mtoma** [comment]
As a side note on testing I think we will have to change the process somehow with a candidate release version or something similar because now all the tests are done on the previous version that is the only one available on CPAN so no new feature can be tested.

----- Original Message -----

**Comment by sandoche2k** [comment]
@matsduf...  @mtoma is right. I think for testing, we need to have the
current version in CPAN.

**Comment by mattias-p** [comment]
@sandoche2k The [SystemTesting](https://github.com/dotse/zonemaster/blob/master/docs/internal-documentation/maintenance/SystemTesting.md) procedure specifies that preliminary distribution tarballs should be installed instead of CPAN releases.

**Comment by sandoche2k** [comment]
@mattias-p that means using "make" ?

**Comment by mattias-p** [comment]
@sandoche2k The way I understand it is that the "distribution tarball" is the tarball that is uploaded to CPAN for release. A "preliminary distribution tarball" is one that is built the same way, but prior to testing and release. I believe [this](https://github.com/dotse/zonemaster/blob/master/docs/internal-documentation/maintenance/ReleaseProcess.md#6-test-to-create-a-distribution-file) is the section where the distribution tarballs get built. This should probably be more clearly documented.

**Comment by sandoche2k** [comment]
@mattias-p as per the reference to create the distribution file, we do the
following

make Makefile.PL
make all
make manifest
make dist

But, in order to install at the end-user for testing, shouldn't it be

make Makefile.PL
make test
make install

I would appreciate your guidance on how to do it?

**Comment by mattias-p** [comment]
I guess we need a new procedure to install a local distribution tarball rather than downloading one from CPAN. I haven't tried but I believe this should do it:

```sh
sudo cpanm /path/to/Zonemaster-WebBackend-VERSION.tar.gz
```

**Comment by matsduf** [comment]
Well, I thought we should test before we update...

I think we should test from the distribution tarball, which should be very close to cpan installation.

**Comment by sandoche2k** [comment]
I followed the process 
```
perl Makefile.PL
make all
make manifest
make dist
```
And then the below. It worked for the engine and the CLI. But not for the backend. Anyone, have an idea?

```
sudo cpan -i Zonemaster-WebBackend-1.0.7.tar.gz
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53_01)
Reading '/home/sandoche/.cpan/Metadata'
  Database was generated on Tue, 06 Dec 2016 16:29:02 GMT
Warning: Cannot install Zonemaster-WebBackend-1.0.7.tar.gz, don't know what it is.
Try the command

    i /Zonemaster-WebBackend-1.0.7.tar.gz/

to find objects with matching identifiers.
CPAN: Time::HiRes loaded ok (v1.9726)
sandoche@vps323914:~/zonemaster-backend$ sudo cpan -i /Zonemaster-WebBackend-1.0.7.tar.gz/
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53_01)
Reading '/home/sandoche/.cpan/Metadata'
  Database was generated on Tue, 06 Dec 2016 16:29:02 GMT
Warning: Cannot install /Zonemaster-WebBackend-1.0.7.tar.gz/, don't know what it is.
Try the command

    i //Zonemaster-WebBackend-1.0.7.tar.gz//

to find objects with matching identifiers.
CPAN: Time::HiRes loaded ok (v1.9726)
```

**Comment by sandoche2k** [comment]
I have the same error as above for CentOS also.

**Comment by mattias-p** [comment]
@sandoche2k The `cpan` man page doesn't say anything about local files, maybe its unable to install tarballs it hasn't downloaded itself? If you look at the `cpanm` man page, installation is clearly supported. Have you tried that?

**Comment by sandoche2k** [comment]
@mattias-p not clear which "local files" are you mentioning. But, as mentioned above, i was able to install "engine" and "CLI". The issue was only with the "backend".

**Comment by mattias-p** [comment]
@sandoche2k The local files I'm referring to are the preliminary distribution tarballs. Did you manage to use `cpan` to install preliminary distribution tarballs for *Engine* and *CLI*? Are you sure it didn't download the latest releases from CPAN? Have you tried to installing preliminary distribution tarballs using `cpanm`?

**Comment by sandoche2k** [comment]
I followed the process

```
git clone "repository"
perl Makefile.PL
make all
make manifest
make dist
````

And then i installed the 'tar.gz' file using 

```
sudo cpan -i file
```

The above process worked for the engine and the CLI and not for the backend

**Comment by mattias-p** [comment]
Forgive me for repeating myself, but do try `cpanm`. It's good for you.

**Comment by sandoche2k** [comment]
In Ubuntu
```
[sandoche@vps323915 zonemaster-backend]$ sudo cpanm Zonemaster-WebBackend-1.0.7.tar.gz
sudo: cpanm: command not found
[sandoche@vps323915 zonemaster-backend]$ locate cpanm
-bash: locate: command not found
[sandoche@vps323915 zonemaster-backend]$ cp
cp              cpan2dist       cpanp           cpansign        cpp
cpan            cpanm           cpanp-run-perl  cpio            cpupower
[sandoche@vps323915 zonemaster-backend]$ cpanm Zonemaster-WebBackend-1.0.7.tar.gz
!
! Can't write to /usr/local/share/perl5 and /usr/local/bin: Installing modules to /home/sandoche/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/local/share/perl5 and /usr/local/bin)
!   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
--> Working on Zonemaster-WebBackend-1.0.7.tar.gz
Fetching file:///home/sandoche/zonemaster-backend/Zonemaster-WebBackend-1.0.7.tar.gz ... OK
Configuring Zonemaster-WebBackend-1.0.7 ... OK
Building and testing Zonemaster-WebBackend-1.0.7 ... OK
Successfully installed Zonemaster-WebBackend-1.0.7
1 distribution installed
````

In CentOS
```
sudo cpanm Zonemaster-WebBackend-1.0.7.tar.gz
--> Working on Zonemaster-WebBackend-1.0.7.tar.gz
Fetching file:///home/sandoche/zonemaster-backend/Zonemaster-WebBackend-1.0.7.tar.gz ... OK
Configuring Zonemaster-WebBackend-1.0.7 ... OK
==> Found dependencies: Net::IP::XS
--> Working on Net::IP::XS
Fetching http://www.cpan.org/authors/id/T/TO/TOMHRR/Net-IP-XS-0.19.tar.gz ... OK
Configuring Net-IP-XS-0.19 ... OK
Building and testing Net-IP-XS-0.19 ... OK
Successfully installed Net-IP-XS-0.19
Building and testing Zonemaster-WebBackend-1.0.7 ... OK
Successfully installed Zonemaster-WebBackend-1.0.7
2 distributions installed
```

**Comment by sandoche2k** [comment]
@mattias-p Installing the backend works with cpanm, but not with cpan. 

But if you see further, in CentOS, it compiles with Net-IP-XS and two distrbutions are installed, whereas in Ubuntu only one distribution is installed.

**Comment by mattias-p** [comment]
@sandoche2k Maybe Net::IP::XS was already installed on your CentOS installation?

**Comment by sandoche2k** [comment]
Yes, it is installed as part of the engine 
sudo cpan -i Hash::Merge Net::IP::XS Net::LDNS JSON Moose

**Comment by sandoche2k** [comment]
@mattias-p i will continue testing. But there is something wrong with the backend, which does not allow it to install from cpan, which has to be investigated.

**Comment by mattias-p** [comment]
@sandoche2k Do you mean installing from CPAN or installing using `cpan`?

**Comment by sandoche2k** [comment]
@mattias-p installing using cpan 

```
sudo cpan -i Zonemaster-WebBackend-1.0.7.tar.gz
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53_01)
Reading '/home/sandoche/.cpan/Metadata'
  Database was generated on Tue, 06 Dec 2016 16:29:02 GMT
Warning: Cannot install Zonemaster-WebBackend-1.0.7.tar.gz, don't know what it is.
Try the command

    i /Zonemaster-WebBackend-1.0.7.tar.gz/

to find objects with matching identifiers.
CPAN: Time::HiRes loaded ok (v1.9726)
sandoche@vps323914:~/zonemaster-backend$ sudo cpan -i /Zonemaster-WebBackend-1.0.7.tar.gz/
Loading internal null logger. Install Log::Log4perl for logging messages
CPAN: Storable loaded ok (v2.53_01)
Reading '/home/sandoche/.cpan/Metadata'
  Database was generated on Tue, 06 Dec 2016 16:29:02 GMT
Warning: Cannot install /Zonemaster-WebBackend-1.0.7.tar.gz/, don't know what it is.
Try the command

    i //Zonemaster-WebBackend-1.0.7.tar.gz//

to find objects with matching identifiers.
CPAN: Time::HiRes loaded ok (v1.9726)
```

**Comment by mattias-p** [comment]
@sandoche2k Please double check your `cpan` usage. I believe it fails to understand what you mean. If you still believe this is a real issue with zonemaster-backend, please file a separate issue (since this one is supposed to be about database creation).

**Comment by sandoche2k** [comment]
With current version, the database files are copied in appropriate directories

**Comment by sandoche2k** [comment]
@mattias-p i too felt the same. But, i have the same result for two
different OS (Ubuntu & CentOS). while the command works for the engine and
the CLI, why it is not working with the backend. And moreover, why it is
working with "cpanm". Yes, creating a new issue
