### ISSUE TITLE
Strange encoding problem

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#27]
The messages are now coming from the translator module in Latin1 (Before it was utf8)

**Comment by pawal** [comment]
Why are we not having UTF-8 everywhere?

**Comment by mtoma** [comment]
No idea, my best guess is that someone changed the locale settings of the server. I'll check this with the sysadmins.
It worked perfectly well with utf8 before and I didn't change anything myself.

----- Original Message -----

**Comment by cdybedahl** [comment]
We do, as far as I know. The GNU gettext system is supposed to be able to transcode according to locale settings, so Michal's theory about the locale on the server getting changed makes sense.

**Comment by pawal** [comment]
Please revert this, we need to have support for cyrillic and kanji. Fix locale on the machine instead.

**Comment by mtoma** [comment]
This is easy to revert anytime.
I prefer to have a working system with French and Swedish now and revert this back to utf8 once I full understand where this problem comes from and ensure it wont happen again.

----- Original Message -----

**Comment by cdybedahl** [comment]
That kind of work would belong naturally on a separate branch.
