### ISSUE TITLE
Rename modules and namespaces

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#284]
4. Rename Zonemaster::WebBackend to Zonemaster::Backend
         a) Separate API and Worker:
                  Zonemaster::Backend::RPCAPI
                  Zonemaster::Backend::TestAgent
5. Daemons should be started by scripts with names reflecting RPCAPI and
TestAgent,respectively.

**Comment by matsduf** [comment]
Fixed by PR #295
