### ISSUE TITLE
Workaround for "query of death" problem

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#287]
A quick fix to block the "query of death" generated by the GUI

**Comment by mtoma** [comment]
https://github.com/dotse/zonemaster-gui/issues/183

**Comment by sandoche2k** [comment]
@mtoma to look for a complete solution

**Comment by matsduf** [comment]
The quick-fix was implemented by PR #325. @mtoma and @sandoche2k, can this issue be closed?
