### ISSUE TITLE
Create documentation on how to install the backend on our supported platforms

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-backend#29]
See issue https://github.com/dotse/zonemaster/issues/137.

**Comment by sandoche2k** [comment]
Following the debian instructions: 

I did not install the following 

"libdbd-mysql-perl" "libdbd-sqlite3-perl" using apt-get and 

sudo cpan -i Store::CouchDB using cpan 

I have the following warnings :
$perl Makefile.pl
Warning: prerequisite DBD::Pg 0 not found.
Warning: prerequisite DBD::SQLite 0 not found.
Warning: prerequisite DBD::mysql 0 not found.
Warning: prerequisite Store::CouchDB 0 not found.
Writing Makefile for zonemaster-backend
Writing MYMETA.yml and MYMETA.json

Is the makefile updated?

**Comment by mtoma** [comment]
The Makefile.PL file was rewritten by Calle. Can you test this now and let me know the status?
I have no clean enough perl environment available to test this.

**Comment by sandoche2k** [comment]
@pawal @mtoma 

perl -MZonemaster::WebBackend::Engine -e 'Zonemaster::WebBackend::Engine->new({ db => "Zonemaster::WebBackend::DB::PostgreSQL"})->{db}->create_db()'
```
using DB:[Zonemaster::WebBackend::DB::PostgreSQL]
DBI connect('database=zonemaster.sqlite;host=localhost','zonemaster',...) failed: FATAL:  database "zonemaster.sqlite" does not exist at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB/PostgreSQL.pm line 24.
```
