### ISSUE TITLE
Create a new index for get_test_history API

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#292]
CREATE INDEX test_results__domain_undelegated ON test_results (domain, undelegated)

Special care must be taken to create this index for the PostgreSQL backend as both fields are part of a JSON column.

**Comment by matsduf** [comment]
@mtoma, can you explain what the problem is that you try to solve with the index?

**Comment by sandoche2k** [comment]
@matsduf, @mattias-p Please check this new commit

**Comment by matsduf** [comment]
Fixed by #324
