### ISSUE TITLE
The get_test_history API call doesn't return all the results

### ISSUE THREAD

**Issue by aabdnn** [dotse/zonemaster-backend#293]
The get_test_history API returns different sets of results for the same domain name. It looks at the key "frontend_params" to determine whether to return the results of regular tests or pre-delegation tests. But this is confusing. It doesn't actually care about the *values* in "nameservers" but just looks to see if *something* is present, and if so, returns pre-delegation results. In fact, it is behaving as if "nameservers" were a boolean, rather than a list.

Furthermore, it looks like the SQLite backend returns different results from the MySQL and PostgreSQL.

IMHO, this API call could, and should, be simpler. It should just take a domain name, and return all the results, both of regular tests, as well as pre-delegated tests. It's the client's responsibility to look at the results, and decide how to interpret and/or display them for a user.

If it is still desired to limit the results to one type or another, then perhaps there should be some kind of key, such as "result_type", which takes one of 3 values (regular, predelegation, all), and returns the appropriate type of result.

**Comment by sandoche2k** [comment]
@mattias-p respond to @aabdnn

**Comment by mattias-p** [comment]
I completely agree with you that there's room for improvement in this method interface.

We're planning to oversee and update the entire backend API in a future release. As part of that effort we'll make it possible to fetch all results for a given zone as a single set.

In the mean time the workaround is to query regular and pre-delegation results separately, and merge the sets in the calling code. I'll also update the API documentation to reflect the current behavior on this topic.

**Comment by mattias-p** [comment]
We should document and implement @aabdnn's suggestion.

In the mean time I suggest we document the MySQL/PostgreSQL behavior and view the SQLite behavior as a bug.

For the record the MySQL/PostgreSQL behavior is to treat the nameservers parameter as a boolean in disguise and return either "regular" or "undelegated" results, and the SQLite behavior is to ignore the nameservers parameter and return "all" results.

**Comment by mattias-p** [comment]
* Deprecate the "ds_list" and "nameservers" parameters.
* Add a new optional parameter "filter" with default value "old_behavior".
* The filter parameter should accept the values "old_behavior", "all", "delegated" and "undelegated".
* The filter value "old_behavior" should be deprecated.
* If filter="old_behavior" is given, the old behavior should be kept. Other filter values should override the old behavior.
* Recommend explicitly specifying a non-deprecated filter value.
* When the "old_behavior" value is removed, the default value of filter will change to "all".

**Comment by pamasse** [comment]
Since we will only keep the "domain" property in the "frontend_params". Could we remove it and put "offset", "limit", "domain" and "filter" in the same level ?
Of course, we must to keep the back compatibility.

Example : 
* `"offset"`: An *unsigned integer*, optional. (default: 0). Position of the first returned element from the database returned list.  
* `"limit"`: An *unsigned integer*, optional. (default: 200). Number of element returned from the *offset* element.
* `"filter"`: A string ["old_behavior" - *Deprecated*, "all", "delegated" and "undelegated"], optional. (default: `old_behavior`)
* `"domain"`: A *domain name*, required.
* `"frontend_params"`: **Deprecated**. An object, optional if `"domain"` is already defined.

**Comment by mattias-p** [comment]
@pamasse I really like the idea, but the new "domain" parameter would have to start out as optional for the sake of backward compatibility.

**Comment by sandoche2k** [comment]
@mattias-p closed ?

**Comment by sandoche2k** [comment]
@pamasse close?
