### ISSUE TITLE
libmodule-build-tiny-perl cannot be installed in Debian 7

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-backend#314]
The installation instruction https://github.com/dotse/zonemaster-backend/blob/master/docs/Installation.md specifies that libmodule-build-tiny-perl installed by apt-get for Debian (and Ubuntu), but that does not work:

```
$ sudo apt-get install libmodule-build-tiny-perl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libmodule-build-tiny-perl
```

The work-around is to include that package, and let it be installed by `cpan` as an indirect dependency.

**Comment by sandoche2k** [comment]
Debian 7 will not be supported as it has reached the end of life.
