### ISSUE TITLE
Add input validation layer

### ISSUE THREAD

**Issue by mattias-p** [dotse/zonemaster-backend#318]
### Background

The Web Backend has an RPC-API through which it receives user input that must not be trusted before it's been validated. This is especially important when the RPC-API is exposed to the Internet. Today the validation of this input is spread out across various implementation layers and it is a non-trivial task to verify that all of it is validated and that the set of accepted values are the correct ones.

### Requirements

It must be easy to verify that the documentation and implementation agree on: 
 * The set of parameters accepted by each API method
 * The data type of each API method parameter
 * The set of values accepted by each data type

It must be easy to verify that no parts of the API method business logic get executed unless all API method arguments were successfully validated.

When a validation error is found, the Web Backend should return a user error response that details the nature of the error and the path into the params data structure where the error was found. _N.B. this requirement is not motivated by the given background, but rather a tacked on usability feature that could theoretically be moved to it's own issue._

### Proposed design

Add data type validation functions:
* For each data type, implement a validation function that returns:
  * On accept: undef
  * On reject: some data structure with details about the first error that was found:
    * The nature of the error. E.g. out of range, wrong basic data type, missing required sub-element, unrecognized sub-element, etc.
    * For errors found within object/array data structures, the path to the erroneous argument.

Add method parameter definitions:
* For each API method, create a parameter definition that maps parameter name to data type validation function.

Update API method dispatch:
* Before branching out to API method business logic:
  1. Retrieve the parameter definition for the requested API method.
  2. Verify that each argument in the request is declared in the parameter definition. Upon an unrecognized parameter, give a "user error" response.
  3. Validate the value of each argument using the corresponding validation function. Upon an invalid parameter, give a "user error" response with a message constructed from details in the validation error result.

### Changelog

2017-12-04: Added section about the goals of this issue. Updated validation functions section in response to comments from @mtoma.
2017-12-05: Added section headers. Expanded upon details of the requirements rather than leaving them implicit in the proposed design. Updated proposed design in response to comment from @matsduf.

**Comment by mattias-p** [comment]
@mtoma @pamasse @matsduf, can you guys have another look at this issue after my updates?

**Comment by matsduf** [comment]
I think the framework looks good. I think that it should be defined that a structure is returned on reject separating the error message from the path to the erroneous element.

**Comment by mattias-p** [comment]
Thanks for reviewing @matsduf. I updated the issue description.

**Comment by sandoche2k** [comment]
The Proposed validation function looks good. @mattias-p, as i understand, the API will call this function to validate the input. Once the input is validated, the API will perform the necessary functions based on the input. My questions are : 

1. Will this module be an independent module?
2. The error messages; will it be needed to adapt as per the input or it will be a generic message
3. Either you or @pamasse who will be implementing this module ?

**Comment by pamasse** [comment]
I found a json validation module that could fit to our needs : [JSON::Validator](http://search.cpan.org/~jhthorsen/JSON-Validator-2.05/lib/JSON/Validator.pm#Supported_schema_formats)
With this module, it's possible to use an api documentation ([swagger](https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI)) to describe input json schemas.

**Comment by pawal** [comment]
I would prefer if any schema used in Zonemaster is based on JSON Schema (draft 4 or 6). Still works with JSON::Validator that you mentioned.

**Comment by matsduf** [comment]
http://json-schema.org/

**Comment by sandoche2k** [comment]
closed by PR #399
