### ISSUE TITLE
ipv4 || ipv4 must be ipv4 || ipv6

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#319]
https://github.com/dotse/zonemaster-backend/blob/fae654d4fc090ae341459bdac97c1ee30bc96732/lib/Zonemaster/Backend/TestAgent.pm#L61

**Comment by sandoche2k** [comment]
@mtoma thanks for resolving this issue.

**Comment by sandoche2k** [comment]
closed by #326
