### ISSUE TITLE
Wrong policy file loaded by TestAgent.pm

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#392]
The PR https://github.com/dotse/zonemaster-engine/pull/360 upgrades the same IP address policy from "Notice" to "Error". But the fix is not viewed from the GUI. The reason seems to be  the file "TestAgent.pm" loads "iana-profile.json" in the line 129 instead of policy.json (https://github.com/dotse/zonemaster-backend/blob/00d29ffc9b39a6fed44d179287bf2367d21cc00c/lib/Zonemaster/Backend/TestAgent.pm)

**Comment by matsduf** [comment]
@sandoche2k, why did you close this issue? The PR #400 has not been merged.

**Comment by sandoche2k** [comment]
@matsduf closing w.r.t to the new commit
