### ISSUE TITLE
Cant test backend properly

### ISSUE THREAD

**Issue by einar** [dotse/zonemaster-backend#45]
I think I might have gotten the backend to (almost) work but I cant test it as I get this when running the client.pl:

Package:Client / Line:66 / JSON::RPC Eror: Can't use string ("nic.fr") as a HASH ref while "strict refs" in use at Engine.pm line 214.

**Comment by mtoma** [comment]
This piece of code is not really meant as any "official" part of the installation instructions. It is more a code snippet. But it doesn't contain the latest version of API calls so I'll fix the contents and move it into a CodeSnippets directory to make it clear what it is supposed to be.
