### ISSUE TITLE
Backend-Installation

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#47]
Clean install - Ubuntu 14.10

After following the Backend install instruction, and on entering the following command 

perl -MEngine -e 'Engine->new({ db => "ZonemasterDB::PostgreSQL"})->{db}->create_db()'
------
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/Engine.pm line 41.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/Engine.pm line 46.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/Engine.pm line 46.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/Engine.pm line 52, <DATA> line 20.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/Engine.pm line 52, <DATA> line 20.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/BackendConfig.pm line 30, <DATA> line 20.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/BackendTranslator.pm line 29, <DATA> line 20.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/BackendTranslator.pm line 34, <DATA> line 20.
Use of uninitialized value $PROD_DIR in concatenation (.) or string at /usr/local/share/perl/5.20.1/BackendTranslator.pm line 34, <DATA> line 20.
using DB:[ZonemasterDB::PostgreSQL]
NOTICE:  table "test_specs" does not exist, skipping
NOTICE:  sequence "test_specs_id_seq" does not exist, skipping
---------

**Comment by mtoma** [comment]
Can I see the result of "pwd" when running this command please?

**Comment by sandoche2k** [comment]
/home/sandoche/zonemaster-backend

The folder which contains  "engine.pm"

**Comment by mtoma** [comment]
This is due to the fact you did a "make install" where the initial installation documentation was asking for a maximum of a "make dist" and untar the archive file in a zonemaster-backend named folder.
Now you have the modules installed in unsupported standard perl directories namely "/usr/local/share/perl/5.20.1/" you will have to erase them all manually. Unless someone know of a method how to uninstall a perl module, as far as I can tell there is none.

**Comment by pawal** [comment]
Which initial installation documentation are you referring to?

**Comment by mtoma** [comment]
https://github.com/dotse/zonemaster-backend/blob/4d442adba3abbbe7b4c0b36916370ae3cfc2f653/Doc/zonemaster-backend-installation-instructions.md

**Comment by sandoche2k** [comment]
*Following the Debian installation instructions and concentrating only on postgresql*

*Existing installation packages that has not been taken into account*
```
1. libdbd-mysql-perl
2.  $ sudo cpan -i Store::CouchDB 
```
*Missing packages in apt-get install and has been added*
```
1. libdbd-pg-perl
2. postgresql 
3. postgresql-contrib
```
Note : libdbd-sqlite3-perl had to be included since make test fails

*Modifications in the Makefile.PL*
Removed the following lines from the makefile
```
'DBD::mysql' => 0,
'Store::CouchDB' => 0,
```

*Followed procedures until "sudo make" dist is done*

Database Configurations
----------------------------------
1. "backend_config.ini" is modified accordingly 

2. A PostgreSQL database with the name specified in the configuration file is created and the database and appropriate access rights are provided

On running the following

```
perl -MEngine -e 'Engine->new({ db => "ZonemasterDB::PostgreSQL"})->{db}->create_db()'
using DB:[ZonemasterDB::PostgreSQL]
NOTICE:  table "test_specs" does not exist, skipping
NOTICE:  sequence "test_specs_id_seq" does not exist, skipping
```

**Comment by sandoche2k** [comment]
Fixed by the pull request 63 from Calle.
