### ISSUE TITLE
Choose which database is needed for the backend

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#54]
Query from Marc (SIDN) : Isn’t it preferable to have an extra option to make test, for which database backend you want to test (and use in production)?

**Comment by mtoma** [comment]
My answer is NO. "make test" must only test against SQLite.
It we want a script to chose/install a database it must be done in a separate INTERACTIVE backend toolbox.
I'm not putting into a makefile something that just erases an entire database.

**Comment by sandoche2k** [comment]
Do we need to install all the three Databases to run the backend : CouchDB,
SQLite and PostgreSQL?

**Comment by mtoma** [comment]
SQLite is a self contained database without any backend, this is the only viable option to be able to do anything meaningful with "make test".
CouchDB is a microscopic perl module that should only pose problems if the user can only installed packaged modules and can't or doesn't want to use CAPN. 
The only real choice to do is between MySQL and PostgreSQL where the user might reasonably not have moth client libraries on the same machine.
This is only a matter of documentation where we need to multiply by 2 or 3 the number of options Ubuntu/Debian/CentOS/FreeBSD x (SQLite+CouchDB/SQLite+MySQL/SQLite+PostgreSQL).
For me it is simpler for the user to install all the modules as they are only client modules for different databases. 

----- Original Message -----

**Comment by sandoche2k** [comment]
Thanks for the response. In this case can you close this issue.
