### ISSUE TITLE
Installation instructions: errors when setting up database

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-backend#68]
```
$ perl -MZonemaster::WebBackend::Engine -e 'Zonemaster::WebBackend::Engine->new({ db => "Zonemaster::WebBackend::DB::PostgreSQL"})->{db}->create_db()'
using DB:[Zonemaster::WebBackend::DB::PostgreSQL]
DBD::SQLite::db do failed: near "SET": syntax error at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB/PostgreSQL.pm line 33.
DBD::SQLite::db do failed: near "SET": syntax error at /usr/local/share/perl/5.18.2/Zonemaster/WebBackend/DB/PostgreSQL.pm line 33.
```

**Comment by cdybedahl** [comment]
You configuration says to use SQLite. Sandoche already reported the exact same thing yesterday.

**Comment by pawal** [comment]
Ah, so the instructions are wrong. @sandoche2k will you update the instructions?

**Comment by sandoche2k** [comment]
No, the instructions are correct. I did not copy the config file in the correct place as indicated in the instructions

**Comment by sandoche2k** [comment]
@pawal Can this issue be closed?

**Comment by pawal** [comment]
I sent a pull request that will close this, once it has been accepted:
https://github.com/dotse/zonemaster-backend/pull/71
