### ISSUE TITLE
Installation instructions: how do I verify the setup?

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-backend#69]
How do I run a test? Or see the status of a backend request?

**Comment by sandoche2k** [comment]
Frankly I did not check this. But is it not in the log files?

**Comment by pawal** [comment]
The log files may contain info about the process, but it doesn't know if the process is currently running. And it has no info on how to run a test :)

**Comment by cdybedahl** [comment]
The "process running" question is a bit hard to define for the backend. There is the web server part (starman according to the docs, but there are other PSGI servers that can be used), which is pretty clear. But the actual testing work is done by processes that deliberately die after 14 minutes 45 seconds and get started by cron every 15 minutes. That bit is trickier to keep track of.

**Comment by mtoma** [comment]
To answer this question the nagios plugin makes a Zonemaster test and checks the result.
If the test contain an answer that looks like a valid Zonemaster answer it considers all the Backend processes are up and running.

**Comment by sandoche2k** [comment]
@pawal Is this question not related to issue 70?

**Comment by pawal** [comment]
Not really. As a user, I am curious about if the service is working as intended. The status in #70 is to know if the service is running or not.

**Comment by sandoche2k** [comment]
One knows, whether the zonemaster engine is working or not when we test a
domain with the zonemaster-cli.

Isn't the same for backend, when we test a domain with the GUI?

**Comment by pawal** [comment]
Maybe. If the user intends to run the GUI, or use the backend for other purposes.

The API is described here: https://github.com/dotse/zonemaster-backend/blob/master/Doc/ZonemasterBackend.md

But there is no example client using it, just to show that it works, and that a test can be performed? It should be trivial to have an example in the installation instruction to show a short example use of the backend using curl or something.

**Comment by mtoma** [comment]
There is the CodeSnippets directory in the zonemaster-backend package.
If you execute the client.pl (using 'perl client.pl') it gives you an answer from the backend (in the particular case of the code currently in the client.pl file onle the result of a simple syntax check).

Is this what you mean by "How do I run a test? Or see the status of a backend request?"

**Comment by einar** [comment]
This documentation needs some serious cleanup as the API has changed quite a bit since it was written; of the 8 distinct API-methods found I could only get 4 to work with the current documentation. Hope we can fix this next week (testing the new mysql-backend is a PAIN as the API is virtually undocumented)... 

#69 should be reopened until all methods can be tested imho.

**Comment by pawal** [comment]
Can you also create a new ticket for the API documentation, @einar?
