### ISSUE TITLE
Installation instructions: stop and restart?

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-backend#70]
How do I control the starman process, how can I see the status, restart or stop it?

**Comment by mtoma** [comment]
You will have to decide if you want the service management scripts for redhat (and other init.d based distributions) added to the repository at some place.
They are used on the web-server machine now but probably need to be changed to run the current modified backend.

**Comment by pawal** [comment]
What is the content of those service management scripts, @mtoma?

I would not like to add distribution specific code to the repository - but it would be great if the interfaces for starting and stopping services are clear. The goal should be to enable the backend to be stopped and started by a distribution specific method (init.d, systemd, whatever). But for now it would be good to just have it in the instructions how to stop the service, or see the status of it (if it's running or not).

**Comment by mtoma** [comment]
Here is the source code of the currently used init.d scripts used on the wbeserver machine:
Can you tell me if it is what you would like to have?

#!/home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/bin/perl -I/home/afnicreg/Zonemaster/zonemaster-backend/
# chkconfig: 2345 20 80 

use warnings;
use strict;
use Daemon::Control;
 
use Cwd qw(abs_path);
 
Daemon::Control->new(
    {
        name      => "Zonemaster backend service",
        lsb_start => '$syslog $remote_fs',
        lsb_stop  => '$syslog',
        lsb_sdesc => 'Zonemaster backend service',
        lsb_desc  => 'Zonemaster backend service',
        path      => abs_path($0),
        directory => '/home/afnicreg/Zonemaster/zonemaster-backend/',
 
        program      => '/home/afnicreg/perl5/perlbrew/perls/perl-5.20.1/bin/starman',
        program_args => [ '--workers', '5', '--listen', '127.0.0.1:5000', '/home/afnicreg/Zonemaster/zonemaster-backend/backend.psgi' ],
 
        user  => 'afnicreg',
        group => 'afnicreg',
 
        pid_file    => '/tmp/starman_backend.pid',
        stderr_file => '/var/log/zonemaster/starman_backend_error.log',
        stdout_file => '/var/log/zonemaster/starman_backend.log',
 
        fork => 2,
 
    }
)->run;


This script (once properly installed) supports the start, stop, restart and status commands.

Is this the requirement here?
