### ISSUE TITLE
MySQL support for the backend

### ISSUE THREAD

**Issue by sandoche2k** [dotse/zonemaster-backend#85]
@cdybedahl Verify the MySQL support for the backend.

**Comment by cdybedahl** [comment]
There is a pull request for this now, which I think works. It could certainly do with more testing.

**Comment by sandoche2k** [comment]
````
sba@sba-VirtualBox:~/zonemaster-backend$ make test
cp lib/Zonemaster/WebBackend/Runner.pm blib/lib/Zonemaster/WebBackend/Runner.pm
cp lib/Zonemaster/WebBackend/DB/MySQL.pm blib/lib/Zonemaster/WebBackend/DB/MySQL.pm
cp lib/Zonemaster/WebBackend/Engine.pm blib/lib/Zonemaster/WebBackend/Engine.pm
cp lib/Zonemaster/WebBackend/DB/SQLite.pm blib/lib/Zonemaster/WebBackend/DB/SQLite.pm
cp lib/Zonemaster/WebBackend/Translator.pm blib/lib/Zonemaster/WebBackend/Translator.pm
cp lib/Zonemaster/WebBackend/DB/PostgreSQL.pm blib/lib/Zonemaster/WebBackend/DB/PostgreSQL.pm
cp lib/Zonemaster/WebBackend/DB.pm blib/lib/Zonemaster/WebBackend/DB.pm
cp lib/Zonemaster/WebBackend/Config.pm blib/lib/Zonemaster/WebBackend/Config.pm
cp script/execute_zonemaster_P10.pl blib/script/execute_zonemaster_P10.pl
/usr/bin/perl "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/execute_zonemaster_P10.pl
cp script/zonemaster_webbackend.psgi blib/script/zonemaster_webbackend.psgi
/usr/bin/perl "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/zonemaster_webbackend.psgi
cp script/execute_zonemaster_P5.pl blib/script/execute_zonemaster_P5.pl
/usr/bin/perl "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/execute_zonemaster_P5.pl
cp script/execute_tests.pl blib/script/execute_tests.pl
/usr/bin/perl "-Iinc" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/execute_tests.pl
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/test01.t ................ 1/? 
#   Failed test 'use Zonemaster::WebBackend::Engine;'
#   at t/test01.t line 8.
#     Tried to use 'Zonemaster::WebBackend::Engine'.
#     Error:  Can't locate Net/LDNS.pm in @INC (you may need to install the Net::LDNS module) (@INC contains: /home/sba/zonemaster-backend/inc /home/sba/zonemaster-backend/blib/lib /home/sba/zonemaster-backend/blib/arch /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/sba/zonemaster-backend/blib/lib/Zonemaster/WebBackend/Engine.pm line 16.
# BEGIN failed--compilation aborted at /home/sba/zonemaster-backend/blib/lib/Zonemaster/WebBackend/Engine.pm line 16.
# Compilation failed in require at (eval 4) line 2.
# BEGIN failed--compilation aborted at (eval 4) line 2.
Can't locate object method "new" via package "Zonemaster::WebBackend::Engine" at t/test01.t line 11.
# Tests were run but no plan was declared and done_testing() was not seen.
t/test01.t ................ Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
t/test_validate_syntax.t .. 1/? 
#   Failed test 'use Zonemaster::WebBackend::Engine;'
#   at t/test_validate_syntax.t line 16.
#     Tried to use 'Zonemaster::WebBackend::Engine'.
#     Error:  Can't locate Net/LDNS.pm in @INC (you may need to install the Net::LDNS module) (@INC contains: /home/sba/zonemaster-backend/inc /home/sba/zonemaster-backend/blib/lib /home/sba/zonemaster-backend/blib/arch /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/sba/zonemaster-backend/blib/lib/Zonemaster/WebBackend/Engine.pm line 16.
# BEGIN failed--compilation aborted at /home/sba/zonemaster-backend/blib/lib/Zonemaster/WebBackend/Engine.pm line 16.
# Compilation failed in require at (eval 9) line 2.
# BEGIN failed--compilation aborted at (eval 9) line 2.
Can't locate object method "new" via package "Zonemaster::WebBackend::Engine" at t/test_validate_syntax.t line 19.
# Tests were run but no plan was declared and done_testing() was not seen.
t/test_validate_syntax.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 

Test Summary Report
-------------------
t/test01.t              (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
t/test_validate_syntax.t (Wstat: 65280 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=2, Tests=2,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.11 cusr  0.02 csys =  0.15 CPU)
Result: FAIL
Failed 2/2 test programs. 2/2 subtests failed.
make: *** [test_dynamic] Error 255
````

**Comment by cdybedahl** [comment]
> On 10 apr 2015, at 12:36, sandoche2k <notifications@github.com> wrote:
> 
> #     Tried to use 'Zonemaster::WebBackend::Engine'.
> #     Error:  Can't locate Net/LDNS.pm in @INC (you may need to install the Net::LDNS module)

— 
Calle Dybedahl
calle.dybedahl@init.se

**Comment by sandoche2k** [comment]
Yes .. But if i have followed all the process of installing
zonemaster-engine, zonemaster-cli, zonemaster-backend.

Hence, installing Net::LDNS module should be added somewhere isnt it ?

**Comment by sandoche2k** [comment]
sudo cpan -i Net::LDNS
[sudo] password for sba:
Reading '/home/sba/.cpan/Metadata'
Reading '/home/sba/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Reading '/home/sba/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Thu, 09 Apr 2015 10:17:02 GMT
..............
  New CPAN.pm version (v2.10) available.
  [Currently running version is v2.00]
  You might want to try
    install CPAN
    reload cpan
  to both upgrade CPAN.pm and run the new version without leaving
  the current session.


..............................................................DONE
Reading '/home/sba/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/sba/.cpan/Metadata
Running install for module 'Net::LDNS'
Running make for C/CD/CDYBED/Net-LDNS-0.75.tar.gz
Fetching with LWP:
http://www.pirbot.com/mirrors/cpan/authors/id/C/CD/CDYBED/Net-LDNS-0.75.tar.gz
Fetching with LWP:
http://www.pirbot.com/mirrors/cpan/authors/id/C/CD/CDYBED/CHECKSUMS
Checksum for
/home/sba/.cpan/sources/authors/id/C/CD/CDYBED/Net-LDNS-0.75.tar.gz ok
Uncompressed
/home/sba/.cpan/sources/authors/id/C/CD/CDYBED/Net-LDNS-0.75.tar.gz
successfully
Using Tar:/bin/tar xf "Net-LDNS-0.75.tar":
Couldn't untar Net-LDNS-0.75.tar: 'Cannot allocate memory'
Package seems to come without Makefile.PL.
  (The test -f "/home/sba/.cpan/build/CDYBED-4bq7Uw/Makefile.PL" returned
false.)
  Writing one on our own (setting NAME to NetLDNS)
  Had problems unarchiving. Please build manually
Running make test
  Make had some problems, won't test
Running make install
  Make had some problems, won't install

**Comment by cdybedahl** [comment]
It shouldn't be possible to install the engine without getting the Net::LDNS module. And that 'Cannot allocate memory' really looks like a problem with the machine you're running this on.

**Comment by sandoche2k** [comment]
While installing zonemaster engine, i get the following error. Is this an
issue local to my VM?

====
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e"
"test_harness(0, 'inc', 'blib/lib', 'blib/arch')" t/*.t
t/axfr.t ........... 1/? AXFR setup error: Could not send or receive,
because of network error at t/axfr.t line 19.
# Tests were run but no plan was declared and done_testing() was not seen.
t/axfr.t ........... Dubious, test returned 115 (wstat 29440, 0x7300)
All 1 subtests passed

**Comment by cdybedahl** [comment]
> On 10 apr 2015, at 14:18, sandoche2k <notifications@github.com> wrote:
> 
> While installing zonemaster engine, i get the following error. Is this an
> issue local to my VM?
> 


Difficult to say. It fails to make a TCP IPv4 connection to a server in New York City (that happens to be a virtual machine rented by me and my wife as a name server for our own domains). 

— 
Calle Dybedahl
calle.dybedahl@init.se
